- name: Generate PMTiles
        run: |
          tippecanoe \
            -o nws_zones.pmtiles \
            -Z4 -z12 \
            --no-simplification-of-shared-nodes \
            --detect-shared-borders \
            --drop-densest-as-needed \
            --extend-zooms-if-still-dropping \
            -L zones_main:zones_main.json \
            -L zones_marine:zones_marine.json \
            -L zones_patches:zones_patches.json
